config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: 'pages#home'

  resources :photo_galleries
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/photo_gallery.rb
class PhotoGallery < ApplicationRecord
  mount_uploader :photo_before, PhotoUploader
  mount_uploader :photo_after, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :create ]
  def create
    contact = Contact.new(contact_params)
    # ContactMailer.contact.deliver_now
    client = Postmark::ApiClient.new(ENV['POSTMARK_API_KEY'])
    client.deliver(
      from: 'contact@nais-maquillage-permanent.fr',
      to: 'contact@nais-maquillage-permanent.fr',
      subject: 'Contact de nais-maquillage-permanent.fr',
      html_body: "
        <strong>CONTACT DE NAIS-MAQUILLAGE-PERMANENT.FR</strong><br><br>
        <strong>Nom :</strong> #{contact.name}<br>
        <strong>Email :</strong> #{contact.email}<br>
        <strong>Message :</strong><br>
        #{contact.message}<br>
      ",
      track_opens: true
    )

    redirect_to "/#contact"
  end

  def contact_params
    params.require(:contact).permit(
      :name,
      :email,
      :message
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    page = params[:page] ? params[:page] : 1
    @photo_gallery = PhotoGallery.new
    @photos        = PhotoGallery.page(page).per(8).order(id: :desc)

    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end

    @contact = Contact.new
  end
end

app/controllers/photo_galleries_controller.rb
class PhotoGalleriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :create, :edit, :update, :destroy ]
  def create
    photo_gallery = PhotoGallery.new(photo_gallery_params)
    photo_gallery.save!
    redirect_to "/#photos"
  end

  def new
    @photo_gallery = PhotoGallery.new
  end

  def edit
    @photo_gallery = PhotoGallery.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @photo_gallery                  = PhotoGallery.find(params[:id])
    @photo_gallery.description      = photo_gallery_params[:description]
    @photo_gallery.has_photo_before = photo_gallery_params[:has_photo_before]
    if photo_gallery_params[:photo_before] != nil
      @photo_gallery.photo_before       = photo_gallery_params[:photo_before]
      @photo_gallery.photo_before_cache = photo_gallery_params[:photo_before_cache]
    end
    if photo_gallery_params[:photo_after] != nil
      @photo_gallery.photo_after       = photo_gallery_params[:photo_after]
      @photo_gallery.photo_after_cache = photo_gallery_params[:photo_after_cache]
    end
    @photo_gallery.save!
    # raise
    redirect_to "/#photos"
  end

  def destroy
    photo_gallery = PhotoGallery.find(params[:id])
    photo_gallery.destroy
    # redirect_to "/#photos"
  end

  def photo_gallery_params
    params.require(:photo_gallery).permit(
      :description,
      :photo_before,
      :photo_after,
      :has_photo_before,
      :photo_before_cache,
      :photo_after_cache
    )
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :js
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :js
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
    # super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naïs - Maquillage permanent à Concarneau</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="google-site-verification" content="FhS_Anc6lbdoC4SgDNFRC9p3kcoekV1qTvMD-KLEnJI" />
    <meta name="description" content="Naïs - Maquillage permanent vous accueille dans un environnement calme et moderne au 33 rue Alain Le Lay à Concarneau. Réunissant toutes ses compétences et ses qualifications pour votre beauté, cette professionnelle de la dermo-pigmentation exerce depuis déjà plusieurs années. A l’écoute de vos attentes pour un résultat qui vous ressemble." />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.css" />
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.js"></script>
  </body>
</html>

app/views/pages/_contact.html.erb
<section id="contact" class="contact-section">
  <div class="wrapper-contact">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 text-center">
          <h2>PRENDRE RENDEZ&#8209;VOUS</h2>
          <h3>Notre expérience au service de votre beauté</h3>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 cards-contact">
          <div class="card-contact text-center">
            <i class="fa fa-envelope-o" aria-hidden="true"></i>
            contact@nais-maquillage-permanent.fr
          </div>
          <div class="card-contact text-center">
            <i class="fa fa-user-o" aria-hidden="true"></i>
            09 53 39 74 46
          </div>
          <div class="card-contact text-center">
            <i class="fa fa-map-marker" aria-hidden="true"></i>
            33 rue Alain Le Lay<br>
            29900 Concarneau
          </div>
        </div>
      </div>

      <div class="row">
        <%= simple_form_for(@contact, html: { class: 'text-center' }) do |f| %>
          <div class="col-xs-12 col-md-4 col-md-offset-2" style="margin-bottom: 14px;">
            <%= f.input :name, label: false, placeholder: "Nom" %>
          </div>
          <div class="col-xs-12 col-md-4 col-md-offset-0" style="margin-bottom: 14px;">
            <%= f.input :email, label: false, placeholder: "Email" %>
          </div>
          <div class="col-xs-12 col-md-8 col-md-offset-2">
            <%= f.input :message, label: false, input_html: { rows: 4 }, placeholder: "Message" %>
          </div>
          <div class="col-xs-12 col-md-8 col-md-offset-2">
            <%= f.submit "ENVOYER", class: "btn btn-contact" %>
          </div>
        <% end %>
        <!-- </div> -->
      </div>
    </div>
  </div>
</section>

app/views/pages/_form_photo.erb
<%= simple_form_for(@photo_gallery) do |f| %>
  <%= f.input :description %>
  <%= f.radio_button :has_photo_before, :true, checked: 'checked' %>
  <%= label :has_photo_before, 'Avec photo avant' %>
  <%= f.radio_button :has_photo_before, :false %>
  <%= label :has_photo_before, 'Sans photo avant' %>
  <%= f.input :photo_before, label: 'Photo avant' %>
  <%= f.input :photo_after, label: 'Photo après' %>
  <%= f.input :photo_before_cache, as: :hidden %>
  <%= f.input :photo_after_cache, as: :hidden %>
  <%= f.submit "#{f.object.new_record? ? 'Ajouter une photo' : 'Modifier une photo'}", class: 'btn btn-success' %>
<% end %>
<div class='photo-gallery-div photo-gallery-form hidden'>
  <div class="photo-gallery-before-div before_thumbnail hidden" style="width: 100%; max-width: 400px; height: 194px;">
    <p class="before-after-flag">AVANT</p>
    <div class="gallery-delete-btn" style="top: 10px; right: 10px;">
      <button type="button" class="btn btn-default btn-danger before_cancel"><i class="fa fa-times"></i></button>
    </div>
  </div>
  <div class="photo-gallery-after-div after_thumbnail hidden" style="width: 100%; max-width: 400px; height: 194px;">
    <p class="before-after-flag">APRÈS</p>
    <div class="gallery-delete-btn" style="top: 10px; right: 10px;">
      <button type="button" class="btn btn-default btn-danger after_cancel"><i class="fa fa-times"></i></button>
    </div>
  </div>
</div>

app/views/pages/_gallery.html.erb
<% @photos.each do |photo| %>
  <div class="col-xs-12 col-sm-6 col-md-3 text-center photo-gallery-item">
    <%=
    if user_signed_in?
      link_to "", class: "photo-gallery-modify" do %>
        <%= render 'photo_div', photo: photo, type: 'page', mode: :admin %>
      <% end
    else
      link_to "#gallery#{photo.id}", {'data-fancybox' => 'gallery', 'data-caption' => photo.description} do %>
          <%= render 'photo_div', photo: photo, type: 'page', mode: :normal %>
        <div id="gallery<%= photo.id %>" style="display: none;">
          <%= render 'photo_div', photo: photo, type: 'fancybox', mode: :normal %>
        </div>
      <% end
    end %>
  </div>
<% end %>

app/views/pages/_photo_div.html.erb
<div class='photo-gallery-div <%= "photo-gallery-div-#{type}" %>'>
  <% if mode == :admin %>
    <div class="gallery-modify-container">
        <%= link_to edit_photo_gallery_path(photo), remote: true, class: 'gallery-modify-btn' do %>
          <i class="fa fa-edit"></i>
        <% end %>
    </div>
    <%= link_to '#', data: {photo: photo.id}, class: 'gallery-delete-btn gallery-delete-btn-to-confirm' do %>
      <i class="fa fa-trash"></i>
    <% end
  end %>
  <% if photo.has_photo_before != false %>
    <div class="photo-gallery-before-div">
      <p class="before-after-flag">AVANT</p>
      <%= cl_image_tag photo.photo_before, height: 194, width: 400, crop: :fill, class: "photo-gallery-before" %>
    </div>
    <div class="photo-gallery-after-div">
      <p class="before-after-flag">APRÈS</p>
      <%= cl_image_tag photo.photo_after, height: 194, width: 400, crop: :fill, class: "photo-gallery-after" %>
    </div>
  <% else %>
    <div class="photo-gallery-after-only-div">
      <%= cl_image_tag photo.photo_after, height: 402, width: 400, crop: :fill, class: "photo-gallery-after" %>
    </div>
  <% end %>
</div>

app/views/pages/_photos.html.erb
<section id="photos" class="photos-section">
  <div class="wrapper-photos">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 text-center">
          <h2>GALERIE</h2>
          <h3>Vous trouverez ici quelques exemples de maquillages permanents réalisés à l'institut</h3>
        </div>
      </div>
      <% if user_signed_in? %>
        <div class="row form-photo">
      <%= render 'form_photo' %>
        </div>
      <% end %>
      <div class="row" id="gallery">
        <%= render 'gallery' %>
      </div>
      <div class="row">
        <div class="col-xs-12 text-center" id="gallery-pagination">
          <%= paginate @photos, remote: true %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_prices.html.erb
<section id="prices" class="prices-section">
  <div class="wrapper-prices">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-sm-6"></div>
        <div class="div-prices col-xs-12 col-sm-6">
          <h2>TARIFS</h2>
          <table>
            <tr>
              <td>Grain de beauté :</td>
              <td class="text-right">80€</td>
            </tr>
            <tr>
              <td>Eyeliner paupière supérieure :</td>
              <td class="text-right">245€&nbsp;<span style="font-size: 10px;">*</span></td>
            </tr>
            <tr>
              <td>Supérieure + inférieure :</td>
              <td class="text-right">285€&nbsp;<span style="font-size: 10px;">*</span></td>
            </tr>
            <tr>
              <td colspan=2 style="padding-top: 16px; font-weight: 400;">LÈVRES</td>
            </tr>
            <tr>
              <td>contour marqué ou fondu :</td>
              <td class="text-right">285€&nbsp;<span style="font-size: 10px;">*</span></td>
            </tr>
            <tr>
              <td>Avec remplissage :</td>
              <td class="text-right">325€&nbsp;<span style="font-size: 10px;">*</span></td>
            </tr>
            <tr>
              <td colspan=2 style="padding-top: 16px; font-weight: 400;">SOURCILS</td>
            </tr>
            <tr>
              <td>densification simple :</td>
              <td class="text-right">245€&nbsp;<span style="font-size: 10px;">*</span></td>
            </tr>
            <tr>
              <td>Densification et correction :</td>
              <td class="text-right">315€&nbsp;<span style="font-size: 10px;">*</span></td>
            </tr>
            <tr>
              <td>Reconstruction complète :</td>
              <td class="text-right">395€&nbsp;<span style="font-size: 10px;">*</span></td>
            </tr>
            <tr>
              <td colspan=2 style="padding-top: 16px; font-style: italic; font-size: 11px;">* les prix sont forfaitaires et tiennent compte d'une retouche le mois suivant.</td>
            </tr>
            <tr>
              <td style="padding-top: 16px;">Retouche supplémentaire avant 6 mois :</td>
              <td class="text-right" style="padding-top: 16px;">120€</td>
            </tr>
            <tr>
              <td>Retouche supplémentaire avant 18 mois :</td>
              <td class="text-right">150€</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper-rdv">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 text-center">
          <h2>VOTRE MAQUILLAGE PERMANENT SUR MESURE</h2>
          <h3>Notre expérience au service de votre beauté</h3>
          <a class="page-scroll btn btn-rdv" href="#contact">PRENDRE RENDEZ-VOUS</a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/_title.html.erb
<section id="title" class="title-section">
  <div class="wrapper-title">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 text-center">
          <%= image_tag "logotitle.png", class: 'logo-title' %>
          <h1>MAQUILLAGE PERMANENT</h1>
          <h2>Salon d'esthétique à Concarneau</h2>
          <a class="page-scroll btn btn-title" href="#services">DÉCOUVRIR NOS OFFRES</a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<%= render 'title' %>
<%= render 'services' %>
<%= render 'prices' %>
<%= render 'photos' %>
<%= render 'contact' %>

app/views/pages/home.js.erb
$('#gallery').html('<%= escape_javascript(raw(render 'gallery')) %>');
$('#gallery-pagination').html('<%= escape_javascript(paginate(@photos, remote: true)) %>');

app/views/photo_galleries/edit.js.erb
$(".form-photo").html("<%= j render 'pages/form_photo', photo_gallery: @photo_gallery %>");
<% if @photo_gallery.has_photo_before %>
  $("#photo_gallery_has_photo_before_true").prop("checked", true);
  $('.photo_gallery_photo_before').show();
  $(".photo_gallery_photo_after label").html("Photo après");
  $('.before_thumbnail').removeClass('hidden');
  $('.before_thumbnail').css('background', 'url("<%= @photo_gallery.photo_before %>")');
  $('.before_thumbnail').css('background-size', 'cover');
  $('.before_thumbnail').css('background-repeat', 'no-repeat');
  $('.before_thumbnail').css('background-position', 'center center');
  $('.photo-gallery-after-div').height('194px');
  $('.before-after-flag').removeClass('hidden');
<% else %>
  $("#photo_gallery_has_photo_before_false").prop("checked", true);
  $('.photo_gallery_photo_before').hide();
  $(".photo_gallery_photo_after label").html("Photo");
  $('.photo-gallery-after-div').height('402px');
  $('.before-after-flag').addClass('hidden');
<% end %>

$('.after_thumbnail').removeClass('hidden');
$('.photo-gallery-form').removeClass('hidden');
$('.after_thumbnail').css('background', 'url("<%= @photo_gallery.photo_after %>")');
$('.after_thumbnail').css('background-size', 'cover');
$('.after_thumbnail').css('background-repeat', 'no-repeat');
$('.after_thumbnail').css('background-position', 'center center');

ForModifyGallery();

app/views/photo_galleries/new.js.erb
$(".form-photo").html("<%= j render 'pages/form_photo', photo_gallery: @photo_gallery %>");

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="wrapper-footer">
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12">Copyright <%= link_to new_user_session_path, remote: true, class: 'admin-link' do %>&copy;<% end %> 2017 <%= link_to "N'Chips Creation", "http://www.nchips.fr", class: 'nchips-link' %></div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header>
  <nav role="navigation" data-big="100" data-small="60">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="#">
          <%= image_tag "logo.png", class: "logo-menu" %>
        </a>
        <div class="bt-menu">
          <i></i><i></i><i></i>
        </div>
      </div>

      <div class="navbar-list-menu">
        <ul>
          <li><a class="page-scroll" href="#title">ACCUEIL</a></li>
          <li><a class="page-scroll" href="#services">SERVICES</a></li>
          <li><a class="page-scroll" href="#prices">TARIFS</a></li>
          <li><a class="page-scroll" href="#photos">PHOTOS</a></li>
          <li><a class="page-scroll" href="#contact">CONTACT</a></li>
          <% if user_signed_in? %>
            <li><%= link_to 'SE DÉCONNECTER', destroy_user_session_path, method: :delete, class: 'btn-logout' %></li>
          <% end %>
          <li><a href="https://www.facebook.com/Na%C3%AFs-Maquillage-Permanent-1266004483495780/"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div id="modal" class="modal fade" style="z-index: 100000;"></div>
</header>